services:
  pokemoncatcher:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
    - sqlserver
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    networks:
    - pokemonnetwork
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Trust123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
        - sqlvolume:/var/opt/mssql
    networks:
        - pokemonnetwork
    restart: unless-stopped

networks:
  pokemonnetwork:
  
volumes:
  sqlvolume:    